id = "elm"
name = "Elm"
description = "Elm support."
version = "0.2.2"
schema_version = 1
authors = ["Zed Industries <support@zed.dev>", "Andrey Kuzmin <hi@unsoundscapes.com>"]
repository = "https://github.com/zed-extensions/elm"

[language_servers.elm-language-server]
name = "elm-language-server"
language = "Elm"

[grammars.elm]
repository = "https://github.com/elm-tooling/tree-sitter-elm"
commit = "09dbf221d7491dc8d8839616b27c21b9c025c457"
